import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseResearch, researchRequest, canonicalURL } from '../lib/research.ts';
import { samples } from '../lib/samples.ts';
import { health } from '../lib/types.ts';
import { inputSchema } from '../lib/validation.ts';
const source='https://www.boj.or.jp/en/mopo/statement.htm';
function fixture(t){return {status:'completed',usage:{input_tokens:1000,output_tokens:500},output:[{type:'web_search_call',status:'completed',action:{sources:[{url:source}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify({summary:'Review',changeSummary:'Baseline',learning:'Inspect dates',nextQuestions:['What is the observation period?'],checks:t.groups.flatMap(g=>g.checks).filter(c=>c.type!=='manual').map(c=>({id:c.id,status:'true',explanation:'Supported by the release.',evidence:[{url:source,title:'BOJ statement',publisher:'BOJ',publishedAt:null,observation:'Policy statement',interpretation:'supports'}]}))})}]}]};}
test('research is forced to search and bounded by output and tool limits',()=>{const r=researchRequest(samples[0]);assert.equal(r.tool_choice,'required');assert.equal(r.model,'gpt-5-nano');assert.equal(r.max_tool_calls,4);assert.equal(r.store,false);assert.equal(r.text.format.strict,true);});
test('untraceable model URLs cannot validate a proposition',()=>{const r=fixture(samples[0]);r.output[0].action.sources=[];const parsed=parseResearch(r,samples[0],'x');assert.ok(parsed.checks.every(c=>c.status==='unclear'&&c.evidence.length===0));});
test('complete source-backed result preserves identity, prior state and usage',()=>{const r=parseResearch(fixture(samples[0]),samples[0],'x');assert.equal(r.checks.length,6);assert.equal(r.checks[0].previousStatus,'pending');assert.equal(r.checks[0].status,'true');assert.equal(r.searchCalls,1);assert.ok(r.estimatedCost<0.011);});
test('missing, duplicate, and extra check IDs fail closed',()=>{for(const mode of ['missing','duplicate','extra']){const r=fixture(samples[0]),part=r.output[1].content[0],p=JSON.parse(part.text);if(mode==='missing')p.checks.pop();if(mode==='duplicate')p.checks[1].id=p.checks[0].id;if(mode==='extra')p.checks[0].id='invented';part.text=JSON.stringify(p);assert.throws(()=>parseResearch(r,samples[0],'x'),/mismatched/);}});
test('incomplete output and skipped web search cannot update checks',()=>{const r=fixture(samples[0]);r.status='incomplete';assert.throws(()=>parseResearch(r,samples[0],'x'),/did not finish/);r.status='completed';r.output.shift();assert.throws(()=>parseResearch(r,samples[0],'x'),/No completed/);});
test('true invalidation and risk conditions are adverse, not positive',()=>{const t=structuredClone(samples[0]);t.groups.find(g=>g.kind==='invalidation').checks[0].status='true';assert.equal(health(t),'Invalidation flagged');t.groups.find(g=>g.kind==='invalidation').checks[0].status='false';t.groups.find(g=>g.kind==='risk').checks[0].status='true';assert.equal(health(t),'Needs attention');});
test('URL normalization rejects executable URLs and strips tracking only',()=>{assert.equal(canonicalURL('javascript:alert(1)'),'');assert.equal(canonicalURL(source+'?utm_source=chatgpt.com'),source);});
test('input limits prevent unbounded research prompts and duplicate checks',()=>{assert.ok(inputSchema.safeParse(samples[0]).success);const t=structuredClone(samples[0]);t.groups[0].checks[0].label='x'.repeat(2500);assert.equal(inputSchema.safeParse(t).success,false);t.groups[0].checks[0].label='valid';t.groups[0].checks[1].id=t.groups[0].checks[0].id;assert.equal(inputSchema.safeParse(t).success,false);});
