import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseResearch, researchRequest, canonicalURL, consumeOpenAIStream } from '../lib/research.ts';
import { samples } from '../lib/samples.ts';
import { inputSchema } from '../lib/validation.ts';
import { parseWindow, checkDeadline, correctLegacyTiming } from '../lib/timing.ts';
import { parseValidation, validationRequest } from '../lib/ai-validation.ts';
const asOf='2026-10-08T00:00:00Z', source='https://www.boj.or.jp/en/mopo/statement.htm';
function fixture(t,status='true'){return {status:'completed',usage:{input_tokens:1000,output_tokens:500},output:[{type:'web_search_call',status:'completed',action:{sources:[{url:source}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify({checks:t.groups.flatMap(g=>g.checks).filter(c=>c.type!=='manual').map(c=>({id:c.id,status,explanation:'Supported by the release.',evidence:[{url:source,title:'BOJ statement',publisher:'BOJ',publishedAt:null,observation:'Policy statement'}]}))})}]}]};}
function futureThesis(){const t=structuredClone(samples[0]);t.horizon='3–6 months, with December 2026 BOJ/Fed meetings as key catalysts';t.createdAt='2026-10-07T17:14:21.388Z';t.groups=t.groups.slice(0,1);t.groups[0].checks=[
 'BOJ policy rate reaches ≥1.50% by December 2026.',
 'Fed policy rate remains ≤4.00% through December 2026.',
 'US–Japan 2-year yield spread narrows by ≥50 bps from the thesis entry level by March 2027.',
 'Japan core CPI remains ≥2.0% YoY for at least 2 of the next 3 monthly releases.',
 'US 2-year Treasury yield falls below 4.40% by March 2027.'
 ].map((label,i)=>({...t.groups[0].checks[0],id:`future-${i}`,label}));return t;}
test('research requires bounded web search and supplies public summary streaming',()=>{const r=researchRequest(samples[0],asOf);assert.equal(r.tool_choice,'required');assert.equal(r.model,'gpt-5-nano');assert.equal(r.max_tool_calls,4);assert.equal(r.store,false);assert.equal(r.text.format.strict,true);assert.equal(r.reasoning.summary,'auto');});
test('untraceable URLs cannot validate an assessable proposition',()=>{const t=structuredClone(samples[0]);t.groups=t.groups.slice(0,1);const r=fixture(t);r.output[0].action.sources=[];assert.ok(parseResearch(r,t,'x',asOf).checks.every(c=>c.status==='unclear'&&c.evidence.length===0));});
test('source-backed current observation preserves identity and usage',()=>{const r=parseResearch(fixture(samples[0]),samples[0],'x',asOf);assert.equal(r.checks.length,6);assert.equal(r.checks[0].previousStatus,'pending');assert.equal(r.checks[0].status,'true');assert.equal(r.searchCalls,1);assert.ok(r.estimatedCost<0.011);});
test('missing, duplicate, and extra check IDs fail closed',()=>{for(const mode of ['missing','duplicate','extra']){const r=fixture(samples[0]),part=r.output[1].content[0],p=JSON.parse(part.text);if(mode==='missing')p.checks.pop();if(mode==='duplicate')p.checks[1].id=p.checks[0].id;if(mode==='extra')p.checks[0].id='invented';part.text=JSON.stringify(p);assert.throws(()=>parseResearch(r,samples[0],'x',asOf),/mismatched/);}});
test('incomplete output and skipped search cannot update checks',()=>{const r=fixture(samples[0]);r.status='incomplete';assert.throws(()=>parseResearch(r,samples[0],'x',asOf),/did not finish/);r.status='completed';r.output.shift();assert.throws(()=>parseResearch(r,samples[0],'x',asOf),/No completed/);});
test('exact USDJPY regression: every future check remains pending for every model verdict',()=>{const t=futureThesis();for(const verdict of ['true','false','unclear','pending']){const r=parseResearch(fixture(t,verdict),t,'x',asOf);assert.ok(r.checks.every(c=>c.status==='pending'),JSON.stringify(r.checks));}const input=JSON.parse(researchRequest(t,asOf).input);assert.ok(input.checks.every(c=>c.pendingRequired));assert.equal(input.checks[2].deadline,'2027-03-31T23:59:59.999Z');});
test('future deadlines stay pending even without sources',()=>{const t=futureThesis(),r=fixture(t);r.output[0].action.sources=[];assert.ok(parseResearch(r,t,'x',asOf).checks.every(c=>c.status==='pending'));});
test('expired deadlines become assessable on new research',()=>{const t=futureThesis(),raw=fixture(t);const part=raw.output[1].content[0],data=JSON.parse(part.text);data.checks.forEach(c=>c.evidence[0].publishedAt='2027-03-31');part.text=JSON.stringify(data);const r=parseResearch(raw,t,'x','2027-04-01T00:00:00Z');assert.ok(r.checks.every(c=>c.status==='true'));});
test('legacy premature results are corrected without altering the original words',()=>{const t=futureThesis();for(const c of t.groups[0].checks){c.status='false';c.evaluatedAt=asOf;}const fixed=correctLegacyTiming(t);assert.ok(fixed.groups[0].checks.every(c=>c.status==='pending'));assert.deepEqual(fixed.groups[0].checks.map(c=>c.label),t.groups[0].checks.map(c=>c.label));assert.equal(t.groups[0].checks[0].status,'false');});
test('latest observations do not inherit a future trade horizon',()=>{const t=futureThesis(),g=t.groups[0];g.checks[0].label='The latest Japanese wage release shows positive year-on-year growth.';assert.equal(checkDeadline(t,g,g.checks[0]),null);assert.equal(parseResearch(fixture(t),t,'x',asOf).checks[0].status,'true');});
test('date parsing handles month, exact day, quarter, relative range and historical comparison',()=>{for(const [s,out] of [['by March 2027','2027-03-31'],['through 2027-03-15','2027-03-15'],['by 15 March 2027','2027-03-15'],['by Q1 2027','2027-03-31'],['next 3–6 months','2027-04-07']])assert.equal(parseWindow(s,'2026-10-07T00:00:00Z')?.toISOString().slice(0,10),out);assert.equal(parseWindow('Revenue grew versus March 2026.','2026-10-07T00:00:00Z'),null);});
test('pre-creation next-event evidence cannot validate a future catalyst',()=>{const t=structuredClone(samples[0]),g=t.groups.find(g=>g.kind==='catalyst');g.checks[0].label='The next BOJ meeting has taken place.';g.window='Next meeting';assert.equal(parseResearch(fixture(t),t,'x',asOf).checks.find(c=>c.id===g.checks[0].id).status,'pending');});
test('safe URLs and bounded unique inputs',()=>{assert.equal(canonicalURL('javascript:alert(1)'),'');assert.equal(canonicalURL(source+'?utm_source=chatgpt.com'),source);assert.ok(inputSchema.safeParse(samples[0]).success);const t=structuredClone(samples[0]);t.groups[0].checks[1].id=t.groups[0].checks[0].id;assert.equal(inputSchema.safeParse(t).success,false);});
test('removed teams and desks cannot be submitted',()=>{for(const [team,desk] of [['Quant','Quant research'],['AI','AI research'],['AMPB','Internship · Seeds'],['AMPB','Internship · Infinity']])assert.equal(inputSchema.safeParse({...samples[0],team,desk}).success,false);});
test('validation retains original text and returns exact field feedback',()=>{const t=structuredClone(samples[0]);t.summary='  Original words.\nSecond line.  ';assert.equal(inputSchema.parse(t).summary,t.summary);assert.equal(validationRequest(t).model,'gpt-5-nano');const output={status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({accepted:false,issues:[{field:'summary',message:'Placeholder text.',suggestion:'Describe the trade.'}]})}]}]};assert.deepEqual(parseValidation(output,t),[{field:'summary',message:'Placeholder text.',suggestion:'Describe the trade.'}]);});
test('stream parser handles arbitrary chunks, emits public summaries and actual source metadata',async()=>{const events=[{type:'response.reasoning_text.delta',delta:'private raw reasoning must not be sent'},{type:'response.reasoning_summary_text.delta',delta:'Checking the observation dates.'},{type:'response.web_search_call.searching'},{type:'response.output_item.done',item:{type:'web_search_call',action:{queries:['BOJ calendar'],sources:[{url:source,title:'BOJ'}]}}},{type:'response.completed',response:fixture(samples[0])}];const wire=events.map(e=>`data: ${JSON.stringify(e)}\n\n`).join(''),encoder=new TextEncoder();const stream=new ReadableStream({start(c){for(let i=0;i<wire.length;i+=17)c.enqueue(encoder.encode(wire.slice(i,i+17)));c.close();}}),out=[];const result=await consumeOpenAIStream(new Response(stream),e=>out.push(e));assert.equal(result.status,'completed');assert.ok(out.some(e=>e.kind==='source'&&e.url===source));assert.ok(out.some(e=>e.kind==='reasoning'));assert.ok(!JSON.stringify(out).includes('private raw'));});
