'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ChevronDown, Filter, LoaderCircle, Pencil, Plus, Search, X } from 'lucide-react';
import { allChecks, desks, kindLabels, newCheck, newGroup } from '@/lib/types';
import type { Check as ThesisCheck, CheckStatus, FieldIssue, Group, GroupKind, ResearchProgress, Team, Thesis } from '@/lib/types';
import { checkDeadline } from '@/lib/timing';
import { checkDisplay, checklistDistribution } from '@/lib/check-display';
import { runCardQueue } from '@/lib/card-research';
import { summarySentence } from '@/lib/summary-text';

type FormInput=Pick<Thesis,'author'|'title'|'team'|'desk'|'instrument'|'direction'|'horizon'|'summary'|'valuation'|'tradePlan'|'groups'>;
type Usage={estimated:number;reserved:number;limit:number;remainingResearches:number};
type Activity={id:string;groupId:string;card:string;index:number;total:number;stage:string;searches:string[];sources:{text:string;url:string}[]};
const statuses:Record<CheckStatus,string>={true:'Verified',unclear:'Unclear',false:'False',pending:'Pending'};
const date=(s:string)=>new Date(s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
class FormError extends Error { constructor(message:string,public issues:FieldIssue[]=[]){super(message);} }
async function api(path:string,method='GET',data?:unknown){
 const r=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});
 const b:any=await r.json();if(!r.ok)throw new FormError(b.error||'Request failed.',b.issues||[]);return b;
}
function StatusIcon({status,kind,researched=false,large=false,label}:{status:CheckStatus;kind:GroupKind;researched?:boolean;large?:boolean;label?:string}){
 const display=checkDisplay(status,kind,researched);
 return <span className={`status-dot ${display.color} ${large?'large':''}`} role="img" aria-label={label||display.label} title={label||display.label}>
  {display.symbol!=='empty'&&<svg viewBox="0 0 20 20" aria-hidden="true"><path d={display.symbol==='tick'?'M5 10l3.5 3.5L15 6.5':display.symbol==='cross'?'M6 6l8 8M14 6l-8 8':'M5 10h10'}/></svg>}
 </span>;
}
function ResearchButton({onClick,disabled,busy=false,label='Research thesis'}:{onClick:()=>void;disabled:boolean;busy?:boolean;label?:string}){
 return <button className="research-button" aria-label={busy?`${label} — running`:label} title={busy?`${label} — running`:label} disabled={disabled} onClick={e=>{e.stopPropagation();onClick();}}>{busy?<LoaderCircle size={21} className="spin"/>:<Search size={21}/>}</button>;
}
export default function Home(){
 const [theses,setTheses]=useState<Thesis[]>([]),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [form,setForm]=useState<Thesis|'new'|null>(null),[tab,setTab]=useState<'monitor'|'original'>('monitor'),[usage,setUsage]=useState<Usage|null>(null),[showUsage,setShowUsage]=useState(false);
 const [filtersOpen,setFiltersOpen]=useState(false),[desk,setDesk]=useState(''),[horizon,setHorizon]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('newest');
 const [activity,setActivity]=useState<Activity|null>(null),[rejected,setRejected]=useState<{id:string;issues:FieldIssue[]}|null>(null);
 const usageRef=useRef<HTMLDivElement>(null),filterRef=useRef<HTMLDivElement>(null),researching=useRef(false);
 async function refreshUsage(){try{setUsage(await api('/api/status'));}catch{}}
 async function load(){setLoading(true);try{setTheses(await api('/api/theses'));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();refreshUsage();const read=()=>{setSelected(new URLSearchParams(location.search).get('thesis'));setTab('monitor');};read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read);},[]);
 useEffect(()=>{function dismiss(e:MouseEvent){if(!usageRef.current?.contains(e.target as Node))setShowUsage(false);if(!filterRef.current?.contains(e.target as Node))setFiltersOpen(false);}function esc(e:KeyboardEvent){if(e.key==='Escape'){setFiltersOpen(false);setShowUsage(false);}}document.addEventListener('mousedown',dismiss);document.addEventListener('keydown',esc);return()=>{document.removeEventListener('mousedown',dismiss);document.removeEventListener('keydown',esc);};},[]);
 function open(id:string|null){history.pushState({},'',id?`?thesis=${encodeURIComponent(id)}`:location.pathname);setSelected(id);setTab('monitor');setError('');setRejected(null);window.scrollTo(0,0);}
 function update(t:Thesis){setTheses(p=>[t,...p.filter(x=>x.id!==t.id)]);}
 async function save(input:FormInput){try{const t=form&&form!=='new'?await api(`/api/theses/${form.id}`,'PATCH',{action:'edit',version:form.version,thesis:input}):await api('/api/theses','POST',input);update(t);setForm(null);open(t.id);}finally{refreshUsage();}}
 async function remove(t:Thesis){await api(`/api/theses/${t.id}`,'DELETE',{version:t.version});setTheses(p=>p.filter(x=>x.id!==t.id));setForm(null);open(null);}
 async function manual(t:Thesis,c:ThesisCheck,s:CheckStatus,note:string){const result=await api(`/api/theses/${t.id}`,'PATCH',{version:t.version,action:'manual',checkId:c.id,status:s,note});update(result);}
 async function research(t:Thesis,groupId?:string){
  if(researching.current)return;researching.current=true;setError('');setRejected(null);
  try{
   await runCardQueue(t,groupId,async(cardId,index,total)=>{
    const group=t.groups.find(g=>g.id===cardId)!;
    const number=t.groups.filter(g=>g.kind===group.kind).findIndex(g=>g.id===cardId)+1;
    setActivity({id:t.id,groupId:cardId,card:`${kindLabels[group.kind]} ${number}`,index,total,stage:'Checking thesis fields…',searches:[],sources:[]});
    let received=false;
    const r=await fetch(`/api/theses/${t.id}/research`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({groupId:cardId})});
    if(!r.ok){const b:any=await r.json();throw new Error(b.error||'Research failed.');}if(!r.body)throw new Error('No research stream was returned.');
    const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';
    function event(raw:string){if(!raw.trim())return;const e=JSON.parse(raw);
     if(e.type==='progress'){const p=e.event as ResearchProgress;setActivity(a=>{if(!a)return a;if(p.kind==='stage')return {...a,stage:p.text};if(p.kind==='reasoning'){const heading=[...p.text.matchAll(/\*\*([^*]+)\*\*/g)].at(-1)?.[1].replace(/\s+/g,' ').trim();return heading?{...a,stage:heading.length>80?heading.slice(0,77).replace(/\s+\S*$/,'')+'…':heading}:a;}if(p.kind==='search')return {...a,searches:[...a.searches,p.text].slice(-8)};if(p.kind==='source'&&p.url&&!a.sources.some(s=>s.url===p.url))return {...a,sources:[...a.sources,{text:p.text,url:p.url}].slice(-16)};return a;});}
     else if(e.type==='result'){received=true;update(e.thesis);}
     else if(e.type==='rejected'){setRejected({id:t.id,issues:e.issues});throw new Error(e.error);}
     else if(e.type==='error')throw new Error(e.error);
    }
    try{while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let i;while((i=buffer.indexOf('\n'))>=0){event(buffer.slice(0,i));buffer=buffer.slice(i+1);}if(done)break;}if(buffer.trim())event(buffer);}finally{reader.releaseLock();}
    if(!received)throw new Error('Research was interrupted. Refresh before trying again.');
   });
  }catch(e){setError((e as Error).message);}finally{researching.current=false;setActivity(null);refreshUsage();}
 }
 const current=theses.find(t=>t.id===selected);
 const visible=theses.filter(t=>(!desk||t.desk===desk)&&(!horizon||t.horizon===horizon)&&(!status||allChecks(t).some(c=>status==='unresearched'?c.status==='pending'&&!c.evaluatedAt:c.status===status&&(status!=='pending'||!!c.evaluatedAt)))).sort((a,b)=>{
  if(sort==='oldest')return a.createdAt.localeCompare(b.createdAt);
  if(sort==='horizon'){const end=(t:Thesis)=>Math.min(...t.groups.flatMap(g=>g.checks.map(c=>checkDeadline(t,g,c)?.getTime()||Infinity)));return end(a)-end(b);}
  return b.createdAt.localeCompare(a.createdAt);
 });
 return <main className={`workspace ${selected?'detail-workspace':''}`}>
  {!selected?<><header className="home-header"><h1>Thesis monitor</h1><div className="toolbar"><div className="filter-anchor" ref={filterRef}><button className={`icon-button ${desk||horizon||status||sort!=='newest'?'is-active':''}`} aria-label="Filter theses" aria-expanded={filtersOpen} title="Filter theses" onClick={()=>setFiltersOpen(!filtersOpen)}><Filter size={20}/></button>{filtersOpen&&<div className="filter-popover"><label>Desk<select value={desk} onChange={e=>setDesk(e.target.value)}><option value="">All desks</option>{Object.entries(desks).map(([team,ds])=><optgroup key={team} label={team}>{ds.map(d=><option key={d}>{d}</option>)}</optgroup>)}</select></label><label>Time horizon<select value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="">All horizons</option>{[...new Set(theses.map(t=>t.horizon).filter(Boolean))].map(h=><option key={h}>{h}</option>)}</select></label><label>Subthesis status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="unresearched">Not researched yet</option>{Object.entries(statuses).map(([s,l])=><option value={s} key={s}>{l}</option>)}</select></label><label>Order<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="horizon">Nearest deadline</option></select></label><button className="text-button" onClick={()=>{setDesk('');setHorizon('');setStatus('');setSort('newest');}}>Reset filters</button></div>}</div><button className="button primary" onClick={()=>setForm('new')}><Plus size={18}/>Add thesis</button></div></header></>:current&&<header className="detail-header"><button className="icon-button back-button" aria-label="Back to theses" title="Back to theses" onClick={()=>open(null)}><ArrowLeft size={23}/></button><div className="detail-identity"><ChecklistDonut thesis={current}/><div className="detail-heading"><div className="metadata">{current.team} / {current.desk} / {current.instrument}</div><h1>{current.title}</h1></div></div><div className="toolbar"><ResearchButton onClick={()=>research(current)} disabled={!!activity} busy={activity?.id===current.id}/><button className="icon-button" disabled={!!activity} title="Edit thesis" aria-label="Edit thesis" onClick={()=>setForm(current)}><Pencil size={20}/></button></div></header>}
  {error&&<div className="error-banner" role="alert"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
  {rejected&&<div className="rejection-panel"><IssueList issues={rejected.issues} thesis={theses.find(t=>t.id===rejected.id)}/><button className="button" onClick={()=>setForm(theses.find(t=>t.id===rejected.id)||null)}>Edit thesis</button></div>}
  {activity&&<ActivityPanel activity={activity}/>}
  {loading?<div className="empty-state">Loading…</div>:selected?current?<>
   <div className="detail-tabs" role="tablist" aria-label="Thesis view"><button id="monitor-tab" role="tab" aria-selected={tab==='monitor'} aria-controls="monitor-panel" onClick={()=>setTab('monitor')}>Thesis monitor</button><button id="original-tab" role="tab" aria-selected={tab==='original'} aria-controls="original-panel" onClick={()=>setTab('original')}>Your thesis</button></div>
   {tab==='monitor'?<div role="tabpanel" id="monitor-panel" aria-labelledby="monitor-tab" className="monitor-list">{current.monitorSummary&&<section className="check-group monitor-summary" aria-labelledby="summary-heading"><h2 id="summary-heading">SUMMARY</h2><p>{summarySentence(current.monitorSummary.text)}</p></section>}{current.groups.map((g,i)=><section className="check-group" key={g.id}><div className="group-heading"><div><span>{kindLabels[g.kind]}{current.groups.filter(x=>x.kind===g.kind).length>1?` ${current.groups.slice(0,i+1).filter(x=>x.kind===g.kind).length}`:''}</span><h2>{g.claim}</h2></div><ResearchButton label={`Research ${kindLabels[g.kind]} ${current.groups.slice(0,i+1).filter(x=>x.kind===g.kind).length}`} onClick={()=>research(current,g.id)} disabled={!!activity||!g.checks.some(c=>c.type!=='manual')} busy={activity?.id===current.id&&activity.groupId===g.id}/></div>{g.checks.map(c=><CheckRow key={c.id} check={c} kind={g.kind} onManual={(s,n)=>manual(current,c,s,n)}/>)}</section>)}</div>:<OriginalThesis thesis={current}/>}
  </>:<div className="empty-state">Thesis not found. <button className="text-button" onClick={()=>open(null)}>Back to theses</button></div>:<div className="thesis-grid">{visible.map(t=><article key={t.id} role="link" tabIndex={0} className="thesis-card" aria-label={`${t.author||'Unnamed'} #${t.authorNumber}: ${t.title}`} onClick={()=>open(t.id)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();open(t.id);}}}><ResearchButton onClick={()=>research(t)} disabled={!!activity} busy={activity?.id===t.id}/><h2>{t.author||'Unnamed'} <span>#{t.authorNumber}</span></h2><p className="card-title">{t.title}</p><div className="card-checks">{t.groups.flatMap(g=>g.checks.map(c=><StatusIcon key={c.id} kind={g.kind} status={c.status} researched={!!c.evaluatedAt} label={`${c.label} — ${checkDisplay(c.status,g.kind,!!c.evaluatedAt).label}`}/>))}</div></article>)}{!visible.length&&<div className="empty-state">{theses.length?'No matching theses.':'No theses yet.'}</div>}</div>}
  {!selected&&<div className="usage-anchor" ref={usageRef}>{showUsage&&<div className="usage-popover">{usage?<><div className="usage-amount"><strong>US${usage.estimated.toFixed(2)}</strong><span>/ ${usage.limit.toFixed(2)} estimated</span></div><progress max={usage.limit} value={usage.reserved} aria-label="Allocated usage"/><div className="usage-detail">${usage.reserved.toFixed(2)} allocated</div><div>≈ {usage.remainingResearches} card researches available</div></>:<p>Usage unavailable.</p>}</div>}<button className="usage-button" aria-expanded={showUsage} onClick={()=>{setShowUsage(!showUsage);refreshUsage();}}>Usage</button></div>}
  {form&&<ThesisForm existing={form==='new'?undefined:form} onClose={()=>setForm(null)} onSave={save} onDelete={remove}/>}
 </main>;
}
function ChecklistDonut({thesis}:{thesis:Thesis}){
 const parts=checklistDistribution(thesis);let offset=0;
 const names={green:'Green',red:'Red',yellow:'Unclear',grey:'Pending or not researched'};
 const description=parts.map(p=>`${names[p.color]} ${p.rounded}%`).join(', ');
 return <div className="checklist-chart"><svg className="checklist-donut" viewBox="0 0 100 100" role="img" aria-label={`Checklist: ${description}`}><title>{description}</title><circle cx="50" cy="50" r="38" fill="none" stroke="var(--border)" strokeWidth="13"/>{parts.map(p=>{const start=offset;offset+=p.percent;return p.count>0?<circle key={p.color} cx="50" cy="50" r="38" fill="none" stroke={`var(--${p.color==='grey'?'pending':p.color})`} strokeWidth="13" pathLength="100" strokeDasharray={`${p.percent} ${100-p.percent}`} strokeDashoffset={-start} transform="rotate(-90 50 50)"/>:null;})}</svg></div>;
}
function ActivityPanel({activity:a}:{activity:Activity}){
 return <section className="activity-panel" aria-live="polite"><div className="activity-stage"><LoaderCircle size={17} className="spin"/><span>{a.card}{a.total>1?` (${a.index}/${a.total})`:""} · {a.stage}</span></div>{a.searches.length>0&&<div className="activity-searches">{a.searches.map((q,i)=><div key={i}><Search size={13}/>{q}</div>)}</div>}{a.sources.length>0&&<div className="activity-sources">{a.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.text}</a>)}</div>}</section>;
}
function CheckRow({check:c,kind,onManual}:{check:ThesisCheck;kind:GroupKind;onManual:(s:CheckStatus,note:string)=>Promise<void>}){
 const [expanded,setExpanded]=useState(false),[status,setStatus]=useState(c.status),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 return <div className={`check-row ${expanded?'expanded':''}`}><button className="check-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><StatusIcon status={c.status} kind={kind} researched={!!c.evaluatedAt} large/><span>{c.label}</span><ChevronDown size={18} className={expanded?'rotated':''}/></button>{expanded&&<div className="check-evidence"><p>{c.explanation||(c.evaluatedAt?'Awaiting the outcome.':c.type==='manual'?'No manual observation yet.':'Not researched yet.')}</p>{c.evaluatedAt&&<div className="evaluated">Checked {date(c.evaluatedAt)}</div>}{c.evidence.length>0&&<div className="source-grid">{c.evidence.map((e,i)=><a key={i} className="source-card" href={e.url} target="_blank" rel="noopener noreferrer"><span>{e.publisher}{e.publishedAt?` · ${e.publishedAt}`:''}</span><strong>{e.title}</strong><p>{e.observation}</p></a>)}</div>}{c.type==='manual'&&<div className="manual-form"><label>Result<select value={status} onChange={e=>setStatus(e.target.value as CheckStatus)}>{Object.entries(statuses).map(([s,l])=><option value={s} key={s}>{checkDisplay(s as CheckStatus,kind,true).label}</option>)}</select></label><label>Evidence<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="E.g. BOJ raised its policy rate to 1.25% on 18 December 2026." maxLength={2000}/></label>{error&&<p className="field-error">{error}</p>}<button className="button" disabled={saving||!note.trim()} onClick={async()=>{setSaving(true);setError('');try{await onManual(status,note);setNote('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>{saving?'Saving…':'Save'}</button></div>}</div>}</div>;
}
function OriginalThesis({thesis:t}:{thesis:Thesis}){
 const text=(label:string,value:string)=>value?<div className="original-field"><h3>{label}</h3><div className="verbatim">{value}</div></div>:null;
 return <div role="tabpanel" id="original-panel" aria-labelledby="original-tab" className="original-thesis">
  <section>{text('Name',t.author)}{text('Thesis title',t.title)}<div className="original-columns">{text('Team',t.team)}{text('Desk',t.desk)}{text('Instrument / research universe',t.instrument)}{text('Direction / expression',t.direction)}{text('Time horizon',t.horizon)}</div>{text('Short summary of the thesis',t.summary)}</section>
  {t.groups.map((g,i)=><section key={g.id}><h2>{kindLabels[g.kind]} {t.groups.slice(0,i+1).filter(x=>x.kind===g.kind).length}</h2>{text('Argument',g.claim)}{text('What does the market believe?',g.marketView)}{text('Why do you see it differently?',g.variantView)}{text(g.kind==='risk'?'Mechanism & mitigation':'Why it matters',g.context)}{text('Expected timing',g.window)}{text('How will you check it?',g.checksText??g.checks.map(c=>(c.type==='manual'?'Manual:':'')+c.label).join('\n'))}</section>)}
  {(t.valuation||t.tradePlan)&&<section>{text(t.team==='AMPB'?'Valuation & assumptions':'Fair value / research framework',t.valuation)}{text('Trade plan',t.tradePlan)}</section>}
 </div>;
}
function fieldLabel(path:string,t?:FormInput){
 const labels:Record<string,string>={author:'Name',title:'Thesis title',instrument:'Instrument',direction:'Direction',horizon:'Time horizon',summary:'Short summary',valuation:'Valuation',tradePlan:'Trade plan',desk:'Desk',groups:'Reasoning'};
 const m=path.match(/^groups\.(\d+)\.(.+)$/);if(!m)return labels[path]||path;
 const g=t?.groups[+m[1]],kind=g?kindLabels[g.kind]:'Reasoning',number=t?.groups.slice(0,+m[1]+1).filter(x=>x.kind===g?.kind).length||+m[1]+1;
 const sub=m[2].match(/^checks\.(\d+)/);return `${kind} ${number} · ${sub?`Subthesis ${+sub[1]+1}`:({claim:'Argument',marketView:'Market view',variantView:'Your view',context:'Context',window:'Timing'} as Record<string,string>)[m[2]]||m[2]}`;
}
function IssueList({issues,thesis,onSelect}:{issues:FieldIssue[];thesis?:FormInput;onSelect?:(path:string)=>void}){return <ul className="issue-list">{issues.map((i,n)=><li key={n}>{onSelect?<button className="text-button" onClick={()=>onSelect(i.field)}>{fieldLabel(i.field,thesis)}</button>:<strong>{fieldLabel(i.field,thesis)}</strong>}<span>{i.message}{i.suggestion?' '+i.suggestion:''}</span></li>)}</ul>;}

function ThesisForm({existing,onClose,onSave,onDelete}:{existing?:Thesis;onClose:()=>void;onSave:(t:FormInput)=>Promise<void>;onDelete:(t:Thesis)=>Promise<void>}){
 const [step,setStep]=useState(0),[input,setInput]=useState<FormInput>(()=>existing?structuredClone(existing):{author:'',title:'',team:'AMPB',desk:desks.AMPB[0],instrument:'',direction:'',horizon:'',summary:'',valuation:'',tradePlan:'',groups:[newGroup('reasoning')]}),[saving,setSaving]=useState(false),[issues,setIssues]=useState<FieldIssue[]>([]),[error,setError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
 const dialogRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';dialogRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!saving){if(confirmDelete)setConfirmDelete(false);else onClose();}if(e.key==='Tab'){const els=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);};},[saving,onClose,confirmDelete]);
 function field<K extends keyof FormInput>(key:K,value:FormInput[K]){setInput(p=>({...p,[key]:value}));}
 function patchGroup(id:string,patch:Partial<Group>){setInput(p=>({...p,groups:p.groups.map(g=>g.id===id?{...g,...patch}:g)}));}
 function checkText(g:Group,text:string){patchGroup(g.id,{checksText:text,checks:text.split('\n').map((label,i)=>({...newCheck(label),id:g.checks[i]?.id||crypto.randomUUID()}))});}
 function go(path:string){const m=path.match(/^groups\.(\d+)/);const s=m?(input.groups[+m[1]]?.kind==='reasoning'?1:2):['valuation','tradePlan'].includes(path)?2:0;setStep(s);requestAnimationFrame(()=>{const el=dialogRef.current?.querySelector<HTMLElement>(`[data-field="${path}"]`);el?.scrollIntoView({block:'center'});el?.focus();});}
 function stepIssues(){const found:FieldIssue[]=[];const add=(field:string)=>found.push({field,message:'This field is required.',suggestion:''});if(step===0){for(const key of ['author','title','instrument','direction','horizon','summary'] as const)if(!input[key].trim())add(key);}if(step===1){input.groups.forEach((g,i)=>{if(g.kind==='reasoning'){if(!g.claim.trim())add(`groups.${i}.claim`);if(!g.checks.some(c=>c.label.trim()))add(`groups.${i}.checks.0.label`);}});}return found;}
 function next(){const found=stepIssues();setIssues(found);if(found.length){setError('Complete the required fields.');return;}setError('');setStep(s=>s+1);dialogRef.current?.querySelector('.form-body')?.scrollTo(0,0);}
 async function submit(){setError('');setIssues([]);setSaving(true);try{const cleaned={...input,groups:input.groups.map(g=>({...g,checks:g.checks.filter(c=>c.label.trim())}))};await onSave(cleaned);}catch(e){setError((e as Error).message);if(e instanceof FormError)setIssues(e.issues);}finally{setSaving(false);}}
 function f(label:string,key:keyof Omit<FormInput,'groups'|'team'>,placeholder:string,textarea=false,required=false,maxLength=2400){return <Field label={label} path={key} value={input[key]} onChange={v=>field(key,v)} placeholder={placeholder} textarea={textarea} required={required} maxLength={maxLength} issues={issues}/>;}
 function renderGroup(g:Group){const i=input.groups.findIndex(x=>x.id===g.id),n=input.groups.slice(0,i+1).filter(x=>x.kind===g.kind).length;const path=`groups.${i}`;
  const gf=(label:string,key:'claim'|'marketView'|'variantView'|'context'|'window',placeholder:string,textarea=true,required=false)=><Field label={label} path={`${path}.${key}`} value={g[key]} onChange={v=>patchGroup(g.id,{[key]:v})} placeholder={placeholder} textarea={textarea} required={required} issues={issues}/>;
  return <div className="form-group" key={g.id}><div className="form-group-heading"><h3>{kindLabels[g.kind]} {n}</h3>{(g.kind!=='reasoning'||input.groups.filter(x=>x.kind==='reasoning').length>1)&&<button className="icon-button" aria-label={`Remove ${g.kind} ${n}`} onClick={()=>field('groups',input.groups.filter(x=>x.id!==g.id))}><X size={18}/></button>}</div>
   {gf(g.kind==='reasoning'?'What is your argument?':g.kind==='catalyst'?'What could unlock the trade?':g.kind==='risk'?'What could go wrong?':'What would make this thesis wrong?','claim',g.kind==='reasoning'?'E.g. Japanese policy normalisation will support the yen.':g.kind==='catalyst'?'E.g. A BOJ rate hike in December could narrow the US–Japan rate gap.':g.kind==='risk'?'E.g. Rising US inflation delays Fed easing.':'E.g. The BOJ abandons further policy normalisation.',true,true)}
   {g.kind==='reasoning'?<div className="form-two">{gf('What does the market believe?','marketView','E.g. The dollar’s yield advantage will keep the yen weak.')}{gf('Why do you see it differently?','variantView','E.g. Markets underestimate the pace of BOJ tightening.')}</div>:gf(g.kind==='risk'?'Mechanism & mitigation':'Why it matters','context',g.kind==='risk'?'E.g. A wider rate gap would support USDJPY. Reduce exposure before CPI releases.':'E.g. A smaller rate gap reduces the return from borrowing yen to hold dollars.')}
   {g.kind==='catalyst'&&gf('Expected timing','window','E.g. By December 2026',false)}
   <Field label="How will you check it?" path={`${path}.checks.0.label`} issues={issues.filter(x=>!x.field.startsWith(`${path}.checks.`)||x.field===`${path}.checks.0.label`)} value={g.checksText??g.checks.map(c=>(c.type==='manual'?'Manual:':'')+c.label).join('\n')} onChange={v=>checkText(g,v)} placeholder={g.kind==='risk'?'E.g. US core CPI YoY increases in two consecutive releases by March 2027.':'E.g. The US–Japan 2-year yield spread falls below 200 bps by March 2027.\nBOJ policy rate reaches 1.50% by December 2026.'} textarea required hint="One subthesis per line. Use “Manual:” for a check you will review yourself."/>
   {issues.filter(x=>x.field.startsWith(`${path}.checks.`)&&x.field!==`${path}.checks.0.label`).map((x,j)=><p className="field-error" key={j}>{fieldLabel(x.field,input)}: {x.message} {x.suggestion}</p>)}
  </div>;
 }
 return <div className="modal-scrim"><div className={`form-modal ${confirmDelete?'delete-modal':''}`} ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="form-title"><header className="form-header"><h2 id="form-title">{confirmDelete?'Delete thesis?':existing?'Edit thesis':'Add thesis'}</h2><button className="icon-button" disabled={saving} aria-label={confirmDelete?'Close deletion confirmation':'Close thesis form'} onClick={()=>confirmDelete?setConfirmDelete(false):onClose()}><X size={23}/></button></header>
 {confirmDelete?<div className="delete-content"><p>Are you sure you want to delete <strong>{existing?.title}</strong>?</p><p>This deletes the thesis and its saved research.</p>{error&&<p role="alert" className="field-error">{error}</p>}<button className="button danger" disabled={saving} onClick={async()=>{if(!existing)return;setSaving(true);setError('');try{await onDelete(existing);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>{saving?'Deleting…':'Confirm delete'}</button></div>:<>
 <div className="form-steps">{['Trade','Reasoning','Full picture'].map((s,i)=><button key={s} className={step===i?'active':''} aria-current={step===i?'step':undefined} onClick={()=>{if(i<step){setStep(i);setError('');}else if(i===step+1)next();}} disabled={saving||i>step+1}>{s}</button>)}</div>
 <div className="form-body"><fieldset disabled={saving}>
  {step===0&&<>{f('Name','author','E.g. Alex Chan',false,true,80)}<div className="form-two"><div className="field"><span>Team</span><div className="team-selector">{(['AMPB','SnT'] as Team[]).map(t=><button type="button" aria-pressed={input.team===t} className={input.team===t?'selected':''} key={t} onClick={()=>setInput(p=>({...p,team:t,desk:desks[t][0]}))}>{t}</button>)}</div></div><label className="field"><span>Desk / team</span><select value={input.desk} onChange={e=>field('desk',e.target.value)}>{desks[input.team].map(d=><option key={d}>{d}</option>)}</select></label></div>{f('Thesis title','title','E.g. A stronger yen as the rate gap narrows',false,true,140)}<div className="form-two">{f('Instrument / research universe','instrument',input.team==='AMPB'?'E.g. NVDA':'E.g. USDJPY or US 10Y',false,true,60)}{f('Direction / expression','direction',input.team==='SnT'?'E.g. Short USD / long JPY':'E.g. Long equity',false,true,100)}</div>{f('Time horizon','horizon','E.g. Through March 2027, or 3–6 months',false,true,200)}{f('Short summary of the thesis','summary','E.g. USDJPY will fall as BOJ tightening narrows the US–Japan rate gap, reducing the dollar’s carry advantage.',true,true)}</>}
  {step===1&&<>{input.groups.filter(g=>g.kind==='reasoning').map(renderGroup)}<button className="button" onClick={()=>field('groups',[...input.groups,newGroup('reasoning')])}>Add reasoning</button></>}
  {step===2&&<>{(['catalyst','risk','invalidation'] as GroupKind[]).map(kind=><section className="form-kind" key={kind}><h3>{kindLabels[kind]}</h3>{input.groups.filter(g=>g.kind===kind).map(renderGroup)}<button className="button" onClick={()=>field('groups',[...input.groups,newGroup(kind)])}>Add {kind==='invalidation'?'invalidation condition':kind}</button></section>)}{f(input.team==='AMPB'?'Valuation & assumptions':'Fair value / research framework','valuation','E.g. Compare USDJPY with the US–Japan 2-year rate spread. Base-case fair value is 150–153.',true)}{f('Trade plan','tradePlan','E.g. Short USDJPY at 157–159, target 150–153, stop at 165. Risk 0.5% of portfolio value.',true)}</>}
 </fieldset></div>
 {error&&<div className="form-errors" role="alert"><p>{error}</p>{issues.length>0&&<IssueList issues={issues} thesis={input} onSelect={go}/>}</div>}
 <footer className="form-footer"><div>{existing&&<button className="text-button delete-link" disabled={saving} onClick={()=>{setConfirmDelete(true);setError('');}}>Delete thesis</button>}</div><div className="toolbar">{step>0&&<button className="button" disabled={saving} onClick={()=>{setStep(s=>s-1);setError('');}}>Back</button>}{step<2?<button className="button primary" onClick={next}>Continue</button>:<button className="button primary" disabled={saving} onClick={submit}>{saving?<><LoaderCircle size={17} className="spin"/>Checking fields…</>:existing?'Save changes':'Create thesis'}</button>}</div></footer>
 </>}
 </div></div>;
}
function Field({label,path,value,onChange,placeholder,textarea,required,hint,maxLength=2400,issues=[]}:{label:string;path:string;value:string;onChange:(v:string)=>void;placeholder:string;textarea?:boolean;required?:boolean;hint?:string;maxLength?:number;issues?:FieldIssue[]}){
 const errors=issues.filter(i=>i.field===path),props={'data-field':path,'aria-invalid':errors.length>0,'aria-describedby':errors.length?`error-${path}`:undefined,value,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>onChange(e.target.value),placeholder,maxLength};
 return <label className="field"><span>{label}{required&&<b> *</b>}</span>{textarea?<textarea {...props} rows={3}/>:<input {...props}/>} {hint&&<small>{hint}</small>}{errors.length>0&&<small id={`error-${path}`} className="field-error">{errors.map(i=>`${i.message} ${i.suggestion}`).join(' ')}</small>}</label>;
}
