'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight, Plus, Search, LayoutGrid, Radio, BookOpen, Archive, X, ChevronDown, ChevronRight, Check, Minus, CircleHelp, Clock3, ExternalLink, LoaderCircle, Sparkles, SlidersHorizontal, FileText, Pencil, Download, Target, AlertTriangle, Leaf, CheckCheck, RotateCcw, Menu, Globe2, CircleDot, MessageSquare, Lightbulb } from 'lucide-react';
import type { Thesis, Group, GroupKind, Check as ThesisCheck, CheckStatus, Review, Team } from '@/lib/types';
import { allChecks, desks, health, kindLabels, newCheck, newGroup } from '@/lib/types';

type Usage={configured:boolean;model:string;limit:number;reserved:number;estimated:number;attempts:number;reservationPerRun:number};
type View='overview'|'evidence'|'journal'|'archived'|'guide';
const date=(s?:string)=>s?new Date(s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
const time=(s:string)=>new Date(s).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const statusLabels:Record<CheckStatus,string>={true:'True',false:'False',unclear:'Unclear',pending:'Pending'};
function StatusIcon({status}:{status:CheckStatus}){const I=status==='true'?Check:status==='false'?X:status==='unclear'?CircleHelp:Clock3;return <I size={14}/>;}
function Status({status,adverse=false}:{status:CheckStatus;adverse?:boolean}){return <span className={`status status-${status} ${adverse&&status==='true'?'status-adverse':''}`}><StatusIcon status={status}/>{statusLabels[status]}</span>;}
function Health({thesis}:{thesis:Thesis}){const h=health(thesis);return <span className={`health ${h==='On track'?'positive':h==='Needs attention'||h==='Invalidation flagged'?'attention':''}`}><span/>{h}</span>;}
async function api(path:string,method='GET',data?:unknown){const r=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});let value:any;try{value=await r.json();}catch{throw new Error('The server could not respond. Please try again.');}if(!r.ok)throw new Error(value.error||'Request failed.');return value;}

export default function App(){
 const [theses,setTheses]=useState<Thesis[]>([]),[loading,setLoading]=useState(true),[view,setView]=useState<View>('overview'),[selected,setSelected]=useState<string|null>(null),[team,setTeam]=useState('All desks'),[query,setQuery]=useState(''),[sort,setSort]=useState('updated'),[form,setForm]=useState<Thesis|'new'|null>(null),[busy,setBusy]=useState<string|null>(null),[toast,setToast]=useState<{text:string;error?:boolean}|null>(null),[usage,setUsage]=useState<Usage|null>(null),[showUsage,setShowUsage]=useState(false),[mobile,setMobile]=useState(false),[error,setError]=useState('');
 const searchRef=useRef<HTMLInputElement>(null);
 async function refresh(){try{const [t,u]=await Promise.all([api('/api/theses'),api('/api/status')]);setTheses(t);setUsage(u);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();const hash=()=>setSelected(location.hash.startsWith('#thesis/')?decodeURIComponent(location.hash.slice(8)):null);hash();window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash);},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),7000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName)){e.preventDefault();searchRef.current?.focus();}if(e.key==='Escape'){setShowUsage(false);setMobile(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 function notify(text:string,error=false){setToast({text,error});}
 function open(t:Thesis){location.hash=`thesis/${encodeURIComponent(t.id)}`;setSelected(t.id);setMobile(false);window.scrollTo(0,0);}
 function navigate(v:View){setView(v);setSelected(null);history.replaceState(null,'',location.pathname);setMobile(false);window.scrollTo(0,0);}
 function update(t:Thesis){setTheses(ts=>[t,...ts.filter(x=>x.id!==t.id)]);}
 async function mutate(t:Thesis,data:Record<string,unknown>){try{const result=await api(`/api/theses/${t.id}`,'PATCH',{...data,version:t.version});update(result);return true;}catch(e){notify((e as Error).message,true);await refresh();return false;}}
 async function research(t:Thesis){if(busy)return;setBusy(t.id);try{const next=await api(`/api/theses/${t.id}/research`,'POST');update(next);notify('Research complete. Open a check to inspect its evidence.');}catch(e){notify((e as Error).message,true);}finally{setBusy(null);api('/api/status').then(setUsage).catch(()=>{});}}
 async function loadExamples(){setBusy('examples');try{await api('/api/theses','POST',{action:'samples'});await refresh();notify('Three example theses added. Their claims have not been verified.');}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}}
 function exportData(){const b=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),theses},null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='traders-ust-theses.json';a.click();URL.revokeObjectURL(u);notify('Workspace exported.');}
 const active=theses.filter(t=>!t.archived),current=theses.find(t=>t.id===selected),checks=active.flatMap(allChecks),attention=active.filter(t=>['Needs attention','Invalidation flagged'].includes(health(t))).length;
 const filtered=theses.filter(t=>(view==='archived'?t.archived:!t.archived)&&(team==='All desks'||t.team===team)&&`${t.title} ${t.instrument} ${t.desk} ${t.summary}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='attention'?Number(['Needs attention','Invalidation flagged'].includes(health(b)))-Number(['Needs attention','Invalidation flagged'].includes(health(a))):b.updatedAt.localeCompare(a.updatedAt));
 const researchButton=(t:Thesis,small=false)=><button className={`button ${small?'research-small':'primary'}`} disabled={!!busy||t.archived} onClick={e=>{e.stopPropagation();research(t);}}>{busy===t.id?<LoaderCircle size={small?14:16} className="spin"/>:<Sparkles size={small?14:16}/>}<span>{busy===t.id?'Researching…':small?'Research':'Research thesis'}</span></button>;
 return <div className="app-shell">
  {mobile&&<div className="mobile-scrim" onClick={()=>setMobile(false)}/>}
  <aside className={`sidebar ${mobile?'open':''}`}>
   <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview');}}><span className="brand-symbol"><span/><span/><span/><span/></span><span>Traders<span className="brand-at">@</span>UST<small>THE RESEARCH WORKSPACE</small></span></a>
   <div className="workspace-label">WORKSPACE <span>PROTOTYPE</span></div>
   <nav aria-label="Main navigation">{([{id:'overview',label:'Thesis monitor',icon:LayoutGrid},{id:'evidence',label:'Evidence feed',icon:Radio},{id:'journal',label:'Review journal',icon:BookOpen}] as const).map(n=><button key={n.id} className={`nav-item ${view===n.id&&!selected?'active':''}`} onClick={()=>navigate(n.id)}><n.icon size={18}/>{n.label}{n.id==='overview'&&<span className="nav-count">{active.length}</span>}</button>)}</nav>
   <div className="nav-divider"/><div className="section-label">RESEARCH DESKS</div>
   <div className="desk-nav">{(['AMPB','SnT','Quant','AI'] as Team[]).map((t,i)=><button key={t} className={team===t?'selected':''} onClick={()=>{setTeam(t);navigate('overview');}}><span className={`desk-dot desk-${i}`}/>{t}<span>{active.filter(a=>a.team===t).length}</span></button>)}</div>
   <button className={`nav-item archived-nav ${view==='archived'?'active':''}`} onClick={()=>navigate('archived')}><Archive size={17}/>Archived theses<span className="nav-count">{theses.filter(t=>t.archived).length}</span></button>
   <div className="sidebar-bottom"><div className="research-note"><span className="note-icon"><Leaf size={18}/></span><strong>Build conviction.<br/>Stay curious.</strong><p>A good thesis is one you can test.</p><button onClick={()=>navigate('guide')}>How this works <ArrowUpRight size={14}/></button></div>
   <button className="usage-link" onClick={()=>setShowUsage(true)}><span className={`connection-dot ${usage?.configured?'connected':''}`}/>{usage?.configured?'Research connected':'Research setup'}<span>Usage <ArrowUpRight size={12}/></span></button>
   <div className="club-signoff"><span className="club-avatar">T</span><div>Traders@UST<small>Shared club workspace</small></div><span className="version">v0.1</span></div></div>
  </aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-toggle icon-button" aria-label="Open menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={12}/><strong>{selected?'Thesis detail':view==='overview'?'Thesis monitor':view==='evidence'?'Evidence feed':view==='journal'?'Review journal':view==='guide'?'How this works':'Archived theses'}</strong></div><div className="topbar-right"><span className="shared-pill"><span/>Shared workspace</span><span className="today">{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span></div></header>
  <main>
   {error&&<div className="error-banner" role="alert"><AlertTriangle size={18}/><span>{error}</span><button onClick={refresh}>Retry</button></div>}
   {loading?<div className="loading-state"><LoaderCircle className="spin" size={28}/><p>Opening your workspace…</p></div>:current?<ThesisDetail key={current.id} thesis={current} onBack={()=>navigate(current.archived?'archived':'overview')} researchButton={researchButton(current)} busy={!!busy} onEdit={()=>setForm(current)} onMutate={data=>mutate(current,data)} notify={notify}/>:selected?<div className="empty-state"><FileText/><h2>Thesis not found</h2><p>It may belong to a different workspace.</p><button className="button" onClick={()=>navigate('overview')}>Back to workspace</button></div>:<>
   {(view==='overview'||view==='archived')&&<>
    <div className="page-heading"><div><div className="eyebrow">THINK CLEARLY. TEST CONTINUOUSLY.</div><h1>{view==='archived'?'The learning stays.':'Every thesis is a hypothesis.'}</h1><p>{view==='archived'?'Revisit closed ideas, their evidence, and the lessons they left behind.':'Keep your reasoning in view. Let the evidence move your conviction.'}</p></div><button className="button primary new-thesis" onClick={()=>setForm('new')}><Plus size={17}/>New thesis</button></div>
    {view==='overview'&&<div className="stats-grid"><Metric label="Active theses" value={active.length} suffix="ideas in motion" icon={<FileText size={17}/>}/><Metric label="Checks to follow" value={checks.length} suffix={`${checks.filter(c=>!!c.evaluatedAt).length} evaluated so far`} icon={<CheckCheck size={17}/>}/><Metric label="Needs attention" value={attention} suffix="challenged assumptions" icon={<CircleDot size={17}/>} attention={attention>0}/><Metric label="Research reviews" value={active.reduce((a,t)=>a+t.reviews.length,0)} suffix="evidence, not intuition" icon={<Globe2 size={17}/>}/></div>}
    <section className="thesis-list"><div className="list-heading"><div className="title-with-count"><h2>{view==='archived'?'Archived theses':'Your theses'}</h2><span>{filtered.length}</span></div><div className="list-controls"><div className="search-input"><Search size={16}/><input ref={searchRef} aria-label="Search theses" placeholder="Search theses…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></div><label className="sort-control"><SlidersHorizontal size={15}/><select aria-label="Sort theses" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Last updated</option><option value="attention">Needs attention</option></select></label></div></div>
    <div className="filter-row"><div className="team-tabs">{['All desks','AMPB','SnT','Quant','AI'].map(t=><button key={t} className={team===t?'selected':''} onClick={()=>setTeam(t)}>{t}</button>)}</div><span className="quiet-label"><span className="tiny-dot"/>Research runs on demand</span></div>
    <div className="thesis-cards">{filtered.map((t,index)=><article key={t.id} className="thesis-card" style={{animationDelay:`${index*55}ms`}}><div className="card-top"><div className="card-tags"><span className={`instrument ${t.team==='AMPB'?'equity':t.desk.startsWith('Rates')?'rates':''}`}>{t.instrument}</span><span className="team-label">{t.team}<span> / </span>{t.desk.replace(/.*· /,'')}</span></div><Health thesis={t}/></div><button className="card-main" onClick={()=>open(t)}><h3>{t.title}<ArrowUpRight size={20}/></h3><p>{t.summary}</p></button><div className="trade-meta"><span>{t.direction}</span><span>{t.horizon||'Open horizon'}</span>{t.sample&&<span className="sample-tag">EXAMPLE</span>}</div><div className="card-bottom"><div className="check-meter"><div className="mini-meter">{(['true','false','unclear','pending'] as CheckStatus[]).map(s=><span key={s} className={`meter-${s}`} style={{flex:Math.max(0.001,allChecks(t).filter(c=>c.status===s).length)}}/>)}</div><span>{allChecks(t).filter(c=>!!c.evaluatedAt).length}<span className="muted"> / {allChecks(t).length} checks reviewed</span></span></div><div className="card-actions"><span className="last-researched">{t.reviews[0]?`Researched ${date(t.reviews[0].createdAt)}`:'Awaiting first research'}</span>{!t.archived&&researchButton(t,true)}<button className="icon-button open-thesis" aria-label={`Open ${t.title}`} onClick={()=>open(t)}><ArrowRight size={17}/></button></div></div></article>)}</div>
    {!filtered.length&&<div className="empty-state"><span className="empty-icon"><FileText size={30}/></span><h2>{theses.length?'No theses here yet.':'A clear argument is a good beginning.'}</h2><p>{theses.length?'Try another desk or search, or start a new thesis.':'Write your first thesis, or explore three clearly labelled examples across FX, equities, and rates.'}</p><div className="button-row"><button className="button primary" onClick={()=>setForm('new')}><Plus size={15}/>Write a thesis</button>{!theses.length&&<button className="button" disabled={!!busy} onClick={loadExamples}>{busy==='examples'?<LoaderCircle className="spin" size={15}/>:<BookOpen size={15}/>}Load example theses</button>}</div></div>}
    </section><div className="workspace-footer"><span><Leaf size={14}/>Better process. Better questions. Better traders.</span><button onClick={exportData}><Download size={14}/>Export workspace</button></div>
   </>}
   {view==='evidence'&&<EvidenceFeed theses={theses} open={open}/>}
   {view==='journal'&&<JournalFeed theses={theses} open={open}/>}
   {view==='guide'&&<Guide onNew={()=>setForm('new')}/>}
   </>}
  </main></div>
  {form&&<ThesisForm existing={form==='new'?undefined:form} onClose={()=>setForm(null)} onSave={async input=>{try{const result=form==='new'?await api('/api/theses','POST',input):await api(`/api/theses/${form.id}`,'PATCH',{action:'edit',version:form.version,thesis:input});update(result);setForm(null);open(result);notify(form==='new'?'Thesis saved. Run research whenever you’re ready.':'Thesis updated. Run research to evaluate the revised checks.');}catch(e){throw e;}}}/>}
  {showUsage&&<div className="modal-scrim" onClick={()=>setShowUsage(false)}><section className="small-modal" role="dialog" aria-modal="true" aria-labelledby="usage-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="Close usage" onClick={()=>setShowUsage(false)}><X size={20}/></button><span className="eyebrow">RESEARCH ALLOWANCE</span><h2 id="usage-title">Small model. Bounded spend.</h2><p>Research uses GPT-5 nano with OpenAI web search. Each click runs one review, with a four-call web-search budget.</p><div className="budget-number">${(usage?.estimated??0).toFixed(3)}<span>estimated API cost</span></div><div className="budget-track"><span style={{width:`${Math.min(100,(usage?.reserved??0)/12*100)}%`}}/></div><div className="budget-details"><span>${(usage?.reserved??0).toFixed(2)} reserved</span><span>$12.00 app allowance</span></div><div className="callout"><strong>{Math.floor((12-(usage?.reserved??0))/.25)} reviews available</strong><p>Each attempt permanently reserves $0.25, including failures, as a conservative spending guard. Actual estimated charges are usually lower. This tracks this app only; your OpenAI project billing is authoritative.</p></div><p className="small muted">One review at a time. A one-minute cooldown prevents accidental repeat requests. There is no automatic research or background polling.</p></section></div>}
  {toast&&<div className={`toast ${toast.error?'error':''}`} role={toast.error?'alert':'status'}>{toast.error?<AlertTriangle size={18}/>:<Check size={18}/>}<span>{toast.text}</span><button aria-label="Dismiss message" onClick={()=>setToast(null)}><X size={16}/></button></div>}
 </div>;
}
function Metric({label,value,suffix,icon,attention}:{label:string;value:number;suffix:string;icon:React.ReactNode;attention?:boolean}){return <div className={`metric ${attention?'metric-attention':''}`}><div className="metric-label">{label}{icon}</div><strong>{String(value).padStart(2,'0')}</strong><span>{suffix}</span></div>;}

function ThesisDetail({thesis:t,onBack,researchButton,busy,onEdit,onMutate,notify}:{thesis:Thesis;onBack:()=>void;researchButton:React.ReactNode;busy:boolean;onEdit:()=>void;onMutate:(d:Record<string,unknown>)=>Promise<boolean>;notify:(t:string,e?:boolean)=>void}){
 const [tab,setTab]=useState('monitor'),[filter,setFilter]=useState('all'),[note,setNote]=useState(''),[saving,setSaving]=useState(false);const checks=allChecks(t),review=t.reviews[0],evaluated=checks.filter(c=>!!c.evaluatedAt).length;
 async function saveNote(){if(!note.trim())return;setSaving(true);if(await onMutate({action:'note',text:note})){setNote('');notify('Reflection added to the journal.');}setSaving(false);}
 return <>
 <button className="back-link" onClick={onBack}><ArrowLeft size={15}/>All theses</button>
 <div className="detail-heading"><div><div className="detail-tags"><span className="instrument">{t.instrument}</span><span className="team-label">{t.team} / {t.desk}</span>{t.sample&&<span className="sample-tag">EXAMPLE THESIS</span>}</div><h1>{t.title}</h1><div className="detail-meta"><span>{t.direction}</span><span>{t.horizon||'Open horizon'}</span><span>Created {date(t.createdAt)}</span></div></div><div className="button-row"><button className="button icon-only" aria-label="Edit thesis" disabled={busy} onClick={onEdit}><Pencil size={16}/></button>{researchButton}</div></div>
 <p className="detail-summary">{t.summary}</p>
 {t.sample&&<div className="sample-notice"><CircleHelp size={14}/>Illustrative thesis for exploring the workflow. Initial claims are hypotheses, not verified market facts.</div>}
 {busy&&<div className="research-progress" role="status"><LoaderCircle className="spin" size={18}/><div><strong>Research is underway</strong><span>Searching the web and checking your propositions. This can take a minute or two.</span></div></div>}
 <div className="detail-tabs">{[['monitor','Claim monitor'],['brief','Thesis brief'],['history','Review history']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}{k==='monitor'&&<span>{checks.length}</span>}{k==='history'&&<span>{t.reviews.length}</span>}</button>)}</div>
 <div className="detail-layout"><div className="detail-main">
 {tab==='monitor'&&<>
 {review&&<div className="review-summary panel"><div className="panel-eyebrow"><Sparkles size={14}/>LATEST RESEARCH <span>{time(review.createdAt)}</span></div><h2>What the evidence says</h2><p>{review.summary}</p><div className="change-summary"><ArrowRight size={15}/><span>{review.changeSummary}</span></div></div>}
 <div className="monitor-heading"><h2>The argument, check by check</h2><select aria-label="Filter checks" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All checks</option><option value="true">True</option><option value="false">False</option><option value="unclear">Unclear</option><option value="pending">Pending</option></select></div>
 {(['reasoning','catalyst','risk','invalidation'] as GroupKind[]).map(kind=>{const gs=t.groups.filter(g=>g.kind===kind && g.checks.some(c=>filter==='all'||c.status===filter));return gs.length>0&&<section className={`monitor-section group-${kind}`} key={kind}><div className="group-section-title"><span className="section-dot"/><h3>{kindLabels[kind]}</h3><span>{gs.length}</span>{kind==='invalidation'&&<small>When to rethink the trade</small>}</div>{gs.map((g,index)=><div className="argument-card" key={g.id}><div className="argument-heading"><span className="argument-number">{String(index+1).padStart(2,'0')}</span><h4>{g.claim}</h4></div>{(g.marketView||g.variantView)&&<div className="variant-grid">{g.marketView&&<div><span>THE MARKET’S VIEW</span><p>{g.marketView}</p></div>}{g.variantView&&<div><span>YOUR DIFFERENT VIEW</span><p>{g.variantView}</p></div>}</div>}{g.context&&<p className="group-context">{g.context}</p>}{g.window&&<div className="window-label"><Clock3 size={13}/>{g.window}</div>}<div className="check-list">{g.checks.filter(c=>filter==='all'||c.status===filter).map(c=><CheckRow key={c.id} check={c} adverse={kind==='risk'||kind==='invalidation'} onManual={(status,note)=>onMutate({action:'manual',checkId:c.id,status,note})}/>)}</div></div>)}</section>})}
 {!t.groups.some(g=>g.checks.some(c=>filter==='all'||c.status===filter))&&<div className="empty-state compact"><CheckCheck/><h3>No {filter} checks</h3><p>Choose another check status to see more.</p></div>}
 </>}
 {tab==='brief'&&<div className="brief-panels"><section className="panel"><div className="panel-eyebrow"><Target size={15}/>ORIGINAL THESIS</div><h2>The idea behind the trade</h2><p className="preserve">{t.summary}</p><dl className="brief-grid"><div><dt>Instrument</dt><dd>{t.instrument}</dd></div><div><dt>Direction</dt><dd>{t.direction}</dd></div><div><dt>Time horizon</dt><dd>{t.horizon||'Not specified'}</dd></div><div><dt>Research desk</dt><dd>{t.team} · {t.desk}</dd></div></dl></section><section className="panel"><div className="panel-eyebrow">VALUATION / FAIR VALUE</div><h2>What is it worth, and why?</h2><p className="preserve">{t.valuation||'No valuation view recorded. Add your assumptions and method when you edit this thesis.'}</p></section><section className="panel"><div className="panel-eyebrow">TRADE IMPLEMENTATION</div><h2>The plan, before the position</h2><p className="preserve">{t.tradePlan||'No implementation plan recorded.'}</p><div className="callout subtle"><strong>A price stop and thesis invalidation answer different questions.</strong><p>Your stop controls trading risk. Invalidation checks test whether the original argument still holds.</p></div></section><section className="panel"><div className="panel-eyebrow">THESIS LIFECYCLE</div><p>{t.archived?'This thesis is archived. Its evidence and reflections remain available.':'Archive this thesis when the trade or research period ends. Your evidence and learning history stay here.'}</p><button className="button" disabled={busy} onClick={()=>onMutate({action:'archive'})}>{t.archived?<RotateCcw size={15}/>:<Archive size={15}/>} {t.archived?'Restore thesis':'Archive thesis'}</button></section></div>}
 {tab==='history'&&<div className="history-list"><h2>A record of changing conviction</h2><p className="muted">Each research run is a snapshot. Previous findings remain here as the thesis evolves.</p>{!t.reviews.length&&<div className="empty-state compact"><BookOpen size={26}/><h3>The first review sets your baseline.</h3><p>Run research to start an evidence history.</p></div>}{t.reviews.map((r,i)=><details className="history-review panel" key={r.id} open={i===0}><summary><span className="history-dot"/><span><strong>Research review {t.reviews.length-i}</strong><small>{time(r.createdAt)} · {r.checks.length} checks · ${r.estimatedCost.toFixed(3)} estimated</small></span><ChevronDown size={16}/></summary><p>{r.summary}</p><div className="change-summary"><ArrowRight size={15}/>{r.changeSummary}</div><div className="history-checks">{r.checks.map(c=><div key={c.id}><span>{c.label||'Check from an earlier thesis version'}</span><div><Status status={c.previousStatus}/><ArrowRight size={12}/><Status status={c.status}/></div><p>{c.explanation}</p>{c.evidence.map((e,j)=><a key={j} href={e.url} target="_blank" rel="noopener noreferrer">{e.title} <ExternalLink size={11}/></a>)}</div>)}</div></details>)}{t.journal.length>0&&<h3 className="journal-subheading">Trader notes & revisions</h3>}{t.journal.map(n=><div className="panel journal-entry" key={n.id}><div className="panel-eyebrow">{n.kind} <span>{time(n.createdAt)}</span></div>{n.kind==='edit'?<details><summary>View the thesis before this revision</summary><div className="previous-thesis"><p>{n.text}</p>{n.previous&&<><h3>{n.previous.title}</h3><p>{n.previous.summary}</p>{n.previous.groups.map(g=><div key={g.id}><strong>{kindLabels[g.kind]} · {g.claim}</strong>{g.marketView&&<p>Market view: {g.marketView}</p>}{g.variantView&&<p>Variant view: {g.variantView}</p>}{g.context&&<p>{g.context}</p>}{g.window&&<p>Timing: {g.window}</p>}{g.checks.map(c=><p key={c.id}>• {c.label} <Status status={c.status}/></p>)}</div>)}<p>Valuation: {n.previous.valuation||"Not recorded"}</p><p>Trade plan: {n.previous.tradePlan||"Not recorded"}</p></>}</div></details>:<p className="preserve">{n.text}</p>}</div>)}</div>}
 </div>
 <aside className="detail-aside"><section className="panel health-panel"><div className="panel-eyebrow">THESIS PULSE</div><Health thesis={t}/><div className="review-ring" style={{background:`conic-gradient(var(--green) ${checks.length?evaluated/checks.length*360:0}deg, var(--line) 0deg)`}}><div><strong>{evaluated}<span>/{checks.length}</span></strong><small>checks evaluated</small></div></div><div className="status-grid">{(['true','false','unclear','pending'] as CheckStatus[]).map(s=><div key={s}><span className={`legend-dot legend-${s}`}/>{statusLabels[s]}<strong>{checks.filter(c=>c.status===s).length}</strong></div>)}</div><p className="pulse-note">Check coverage, not a conviction score. True risk and invalidation checks flag adverse developments.</p><div className="last-check"><Clock3 size={13}/>{review?`Last research ${time(review.createdAt)}`:'No research run yet'}</div></section>
 <section className="panel learning-panel"><div className="panel-eyebrow"><Lightbulb size={15}/>THE LEARNING EDGE</div><h3>{review?'A lesson to carry forward':'Test the weakest link.'}</h3><p>{review?.learning||'Which assumption would change your mind? Write it down before searching for evidence.'}</p>{review?.nextQuestions.length?<div className="next-questions"><strong>Ask next</strong>{review.nextQuestions.map((q,i)=><p key={i}><span>{i+1}.</span>{q}</p>)}</div>:null}</section>
 <section className="panel reflection-panel"><div className="panel-eyebrow"><Pencil size={14}/>YOUR REFLECTION</div><h3>What changed your mind?</h3><textarea aria-label="Your reflection" value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} placeholder="What did you miss? What would you look for earlier next time?" rows={4}/><button className="button" onClick={saveNote} disabled={!note.trim()||saving}>{saving?<LoaderCircle size={14} className="spin"/>:<Plus size={14}/>}Save reflection</button><small>Saved to this thesis’s review history.</small></section>
 </aside></div>
 </>;
}
function CheckRow({check:c,adverse,onManual}:{check:ThesisCheck;adverse:boolean;onManual:(s:string,n:string)=>Promise<boolean>}){
 const [expanded,setExpanded]=useState(false),[note,setNote]=useState(''),[status,setStatus]=useState<CheckStatus>(c.status),[saving,setSaving]=useState(false);
 return <div className={`check-row ${expanded?'expanded':''}`}><button className="check-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><span className={`check-state-icon ${c.status} ${adverse&&c.status==='true'?'adverse':''}`}><StatusIcon status={c.status}/></span><span className="check-label">{c.label}<small>{c.type} check{c.deadline?` · by ${c.deadline}`:''}{adverse&&c.status==='true'?' · adverse signal':''}</small></span><Status status={c.status} adverse={adverse}/><ChevronDown size={15} className={expanded?'rotated':''}/></button>{expanded&&<div className="check-evidence"><p>{c.explanation|| (c.type==='manual'?'This check needs a trader’s observation. Add a note and mark the result below.':'Not evaluated yet. Run research to search for evidence on this exact proposition.')}</p>{c.evaluatedAt&&<span className="evidence-date">Evaluated {time(c.evaluatedAt)}</span>}{c.evidence.map((e,i)=><a key={i} className="source-card" href={e.url} target="_blank" rel="noopener noreferrer"><div><span className={`evidence-sentiment ${e.interpretation}`}>{e.interpretation}</span><span>{e.publisher}{e.publishedAt?` · ${e.publishedAt}`:' · Publication date unavailable'}</span><ExternalLink size={13}/></div><strong>{e.title}</strong><p>{e.observation}</p><small>{new URL(e.url).hostname}</small></a>)}{c.type==='manual'&&<div className="manual-check-form"><label>Observed result<select value={status} onChange={e=>setStatus(e.target.value as CheckStatus)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Evidence / reasoning<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you observe? Include a source or the period you checked." maxLength={2000}/></label><button className="button" disabled={!note.trim()||saving} onClick={async()=>{setSaving(true);if(await onManual(status,note))setNote('');setSaving(false);}}>Save manual check</button></div>}</div>}</div>;
}

function EvidenceFeed({theses,open}:{theses:Thesis[];open:(t:Thesis)=>void}){const entries=theses.flatMap(t=>t.reviews.flatMap(r=>r.checks.flatMap(c=>c.evidence.map((e,i)=>({t,r,c,e,id:`${r.id}-${c.id}-${i}`}))))).sort((a,b)=>b.r.createdAt.localeCompare(a.r.createdAt));return <><div className="page-heading"><div><div className="eyebrow">FOLLOW THE EVIDENCE</div><h1>Every claim needs a source.</h1><p>News and documents discovered in your research, connected to the checks they inform.</p></div></div>{!entries.length?<div className="empty-state"><Radio size={30}/><h2>Your first source starts here.</h2><p>Run research on a thesis to collect supporting and contradicting evidence. Nothing is fetched in the background.</p></div>:<div className="feed-list">{entries.map(({t,r,c,e,id})=><article className="panel feed-entry" key={id}><div className="feed-meta"><button onClick={()=>open(t)}>{t.instrument} <ArrowUpRight size={13}/></button><span>{time(r.createdAt)}</span><span className={`evidence-sentiment ${e.interpretation}`}>{e.interpretation}</span></div><a className="feed-title" href={e.url} target="_blank" rel="noopener noreferrer">{e.title}<ExternalLink size={16}/></a><p>{e.observation}</p><span className="muted small">{e.publisher} · {e.publishedAt||'Publication date unavailable'}</span><div className="feed-check"><CheckCheck size={14}/>{c.label||'Check from a previous version'}<Status status={c.status}/></div></article>)}</div>}</>;}
function JournalFeed({theses,open}:{theses:Thesis[];open:(t:Thesis)=>void}){const entries=theses.flatMap(t=>[...t.journal.map(j=>({t,id:j.id,date:j.createdAt,title:j.kind==='edit'?'Thesis revised':j.kind==='manual'?'Manual observation':'Trader reflection',text:j.kind==='edit'?'The argument was revised and checks reset. Open the thesis for the previous version.':j.text})),...t.reviews.map(r=>({t,id:r.id,date:r.createdAt,title:'Research lesson',text:r.learning}))]).sort((a,b)=>b.date.localeCompare(a.date));return <><div className="page-heading"><div><div className="eyebrow">A BETTER PROCESS, OVER TIME</div><h1>Keep the lesson. Revisit the logic.</h1><p>Your reflections and research lessons, across every thesis in the workspace.</p></div></div>{!entries.length?<div className="empty-state"><BookOpen size={30}/><h2>Make your thinking visible.</h2><p>Add a reflection on any thesis, or run your first research review to begin your learning journal.</p></div>:<div className="journal-feed">{entries.map(e=><article key={e.id} className="panel"><div className="panel-eyebrow">{e.title}<span>{time(e.date)}</span></div><p className="preserve">{e.text}</p><button className="text-link" onClick={()=>open(e.t)}>{e.t.title}<ArrowUpRight size={14}/></button></article>)}</div>}</>;}
function Guide({onNew}:{onNew:()=>void}){return <><div className="page-heading"><div><div className="eyebrow">A RESEARCH HABIT, NOT A SIGNAL SERVICE</div><h1>Make your thesis testable.</h1><p>A lightweight loop for building and reviewing investment arguments.</p></div></div><div className="guide-grid">{[{n:'01',title:'Write the argument',text:'Capture your trade, the market’s view, and why you see it differently. Keep valuation and the trade plan alongside your reasoning.'},{n:'02',title:'Name the checks',text:'Attach specific, testable propositions to reasoning, catalysts, risks, and invalidation conditions. Include a metric, period, and threshold when you have them.'},{n:'03',title:'Follow the evidence',text:'Run research on demand. Web search finds sources; the model evaluates each proposition. Expand a check to inspect the source and decide whether the interpretation holds.'},{n:'04',title:'Save the lesson',text:'Compare research reviews and write a reflection. Archive a finished thesis without losing its history. What you learn should inform the next idea.'}].map(x=><section className="panel" key={x.n}><span className="guide-number">{x.n}</span><h2>{x.title}</h2><p>{x.text}</p></section>)}</div><div className="panel guide-status"><h2>Read the check, then the result.</h2><div className="guide-status-grid">{[['true','Evidence establishes the proposition.'],['false','Evidence establishes the opposite.'],['unclear','Evidence is missing, stale, or conflicting.'],['pending','The event or observation window is still ahead.']].map(([s,d])=><div key={s}><Status status={s as CheckStatus}/><p>{d}</p></div>)}</div><div className="callout"><strong>A true invalidation condition is a reason to reassess.</strong><p>Checks measure propositions. They do not measure the probability that a trade will succeed. Web research is a dated review, not a live price feed or an automated stop-loss system.</p></div><button className="button primary" onClick={onNew}><Plus size={15}/>Write your first thesis</button></div></>;}

type FormInput=Pick<Thesis,'title'|'team'|'desk'|'instrument'|'direction'|'horizon'|'summary'|'valuation'|'tradePlan'|'groups'>;
function ThesisForm({existing,onClose,onSave}:{existing?:Thesis;onClose:()=>void;onSave:(t:FormInput)=>Promise<void>}){
 const [step,setStep]=useState(0),[input,setInput]=useState<FormInput>(()=>existing?structuredClone(existing):{title:'',team:'AMPB',desk:desks.AMPB[0],instrument:'',direction:'',horizon:'',summary:'',valuation:'',tradePlan:'',groups:[newGroup('reasoning')]}),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const dialogRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';dialogRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!saving)onClose();if(e.key==='Tab'){const els=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);};},[saving,onClose]);
 function field<K extends keyof FormInput>(key:K,value:FormInput[K]){setInput(p=>({...p,[key]:value}));}
 function patchGroup(id:string,patch:Partial<Group>){setInput(p=>({...p,groups:p.groups.map(g=>g.id===id?{...g,...patch}:g)}));}
 function checkText(g:Group,text:string){const labels=text.split('\n');const old=g.checks;patchGroup(g.id,{checks:labels.map((label,i)=>({...newCheck(label),id:old[i]?.id||crypto.randomUUID()}))});}
 function validStep(){if(step===0&&(!input.title.trim()||!input.instrument.trim()||!input.direction.trim()||!input.summary.trim()))return 'Add a title, instrument, direction, and thesis summary.';if(step===1&&input.groups.filter(g=>g.kind==='reasoning').some(g=>!g.claim.trim()||!g.checks.some(c=>c.label.trim())))return 'Each reasoning point needs an argument and at least one check.';return '';}
 function next(){const e=validStep();if(e){setError(e);return;}setError('');setStep(s=>s+1);dialogRef.current?.querySelector('.form-body')?.scrollTo(0,0);}
 async function submit(){setError('');setSaving(true);try{const cleaned={...input,groups:input.groups.filter(g=>g.kind==='reasoning'||g.claim.trim()).map(g=>({...g,checks:g.checks.filter(c=>c.label.trim()).map(c=>({...c,label:c.label.trim()}))}))};if(cleaned.groups.some(g=>!g.checks.length))throw new Error('Every argument, catalyst, risk, and invalidation condition needs at least one check.');await onSave(cleaned);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 function renderGroup(g:Group,i:number){return <div className="form-group-card" key={g.id}><div className="form-group-title"><strong>{g.kind==='reasoning'?`Reasoning point ${i+1}`:g.kind==='catalyst'?'Catalyst':g.kind==='risk'?'Risk':'Invalidation condition'}</strong>{(g.kind!=='reasoning'||input.groups.filter(x=>x.kind==='reasoning').length>1)&&<button type="button" className="icon-button" aria-label="Remove argument" onClick={()=>field('groups',input.groups.filter(x=>x.id!==g.id))}><X size={16}/></button>}</div><Field label={g.kind==='reasoning'?'What is your argument?':g.kind==='catalyst'?'What could unlock the trade?':g.kind==='risk'?'What could go wrong?':'What would make this thesis wrong?'} value={g.claim} onChange={v=>patchGroup(g.id,{claim:v})} placeholder={g.kind==='reasoning'?'E.g. Japanese policy normalisation will support the yen.':g.kind==='invalidation'?'E.g. The BOJ abandons further policy normalisation.':'Describe it in your own words.'} textarea required/>{g.kind==='reasoning'?<div className="form-two"><Field label="What does the market believe?" value={g.marketView} onChange={v=>patchGroup(g.id,{marketView:v})} placeholder="The consensus you disagree with…" textarea/><Field label="Why do you see it differently?" value={g.variantView} onChange={v=>patchGroup(g.id,{variantView:v})} placeholder="Your variant view…" textarea/></div>:<Field label={g.kind==='risk'?'Mechanism & mitigation':'Why it matters'} value={g.context} onChange={v=>patchGroup(g.id,{context:v})} placeholder="How does this affect the argument?" textarea/>}{g.kind==='catalyst'&&<Field label="Expected timing" value={g.window} onChange={v=>patchGroup(g.id,{window:v})} placeholder="E.g. the next BOJ meeting, or by end of Q4 2026"/>}<Field label="How will you check it?" hint="One testable proposition per line. Include thresholds and periods. Prefix “Manual:” for checks you will review yourself." value={g.checks.map(c=>(c.type==='manual'?'Manual: ':'')+c.label).join('\n')} onChange={v=>checkText(g,v)} placeholder={g.kind==='risk'?'E.g. US core CPI YoY has increased for two consecutive releases.':'E.g. The US–Japan 2-year yield spread narrows below 200 bps by December 2026.'} textarea required/></div>;}
 return <div className="modal-scrim form-scrim"><div className="form-modal" ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="form-title"><header className="form-header"><div><span className="eyebrow">YOUR NEXT INVESTMENT ARGUMENT</span><h2 id="form-title">{existing?'Refine your thesis.':'Start with a clear idea.'}</h2></div><button className="icon-button" disabled={saving} aria-label="Close thesis form" onClick={onClose}><X size={21}/></button></header><div className="form-steps">{['The trade','The reasoning','The full picture'].map((s,i)=><button key={s} className={`${step===i?'active':''} ${step>i?'done':''}`} onClick={()=>{if(i<step){setStep(i);setError('');}}} disabled={i>step}><span>{step>i?<Check size={12}/>:i+1}</span>{s}</button>)}</div><div className="form-body"><div className="form-content">
 {step===0&&<><div className="field"><label>Research team</label><div className="team-selector">{(['AMPB','SnT','Quant','AI'] as Team[]).map(t=><button type="button" className={input.team===t?'selected':''} key={t} onClick={()=>setInput(p=>({...p,team:t,desk:desks[t][0]}))}>{t}{input.team===t&&<Check size={14}/>}</button>)}</div></div><label className="field"><span>Desk / team</span><select value={input.desk} onChange={e=>field('desk',e.target.value)}>{desks[input.team].map(d=><option key={d}>{d}</option>)}</select></label><Field label="Thesis title" required value={input.title} onChange={v=>field('title',v)} placeholder="A short name for your idea" maxLength={140}/><div className="form-two"><Field label="Instrument / research universe" required value={input.instrument} onChange={v=>field('instrument',v)} placeholder={input.team==='AMPB'?'E.g. NVDA':input.team==='SnT'?'E.g. USDJPY or US 10Y':'E.g. US liquid equities'}/><Field label="Direction / expression" required value={input.direction} onChange={v=>field('direction',v)} placeholder={input.team==='SnT'?'E.g. short USD / long JPY':'E.g. long equity'}/></div><Field label="Time horizon" value={input.horizon} onChange={v=>field('horizon',v)} placeholder="E.g. 3–6 months, through the next two earnings releases"/><Field label="The thesis, in your own words" required value={input.summary} onChange={v=>field('summary',v)} placeholder="What do you expect to happen, why, and how does the trade benefit?" textarea/></>}
 {step===1&&<><div className="form-section-intro"><h3>What has to be true?</h3><p>Separate your argument from the evidence that would test it.</p></div>{input.groups.filter(g=>g.kind==='reasoning').map(renderGroup)}<button className="button add-group" onClick={()=>field('groups',[...input.groups,newGroup('reasoning')])}><Plus size={15}/>Add a reasoning point</button></>}
 {step===2&&<><div className="form-section-intro"><h3>Give the idea boundaries.</h3><p>Optional context makes the research more useful. Add only what matters to this trade.</p></div>{(['catalyst','risk','invalidation'] as GroupKind[]).map(kind=><section className="form-kind-section" key={kind}><h3>{kindLabels[kind]}</h3>{input.groups.filter(g=>g.kind===kind).map(renderGroup)}<button className="button add-group" onClick={()=>field('groups',[...input.groups,newGroup(kind)])}><Plus size={15}/>Add {kind==='invalidation'?'an invalidation condition':`a ${kind}`}</button></section>)}<Field label={input.team==='AMPB'?'Valuation & assumptions':'Fair value / research framework'} value={input.valuation} onChange={v=>field('valuation',v)} placeholder="Your method, assumptions, comparison set, and fair-value view…" textarea/><Field label="Trade plan" value={input.tradePlan} onChange={v=>field('tradePlan',v)} placeholder="Entry, target, stop, position sizing, and implementation notes. Use your own words." textarea/>{existing&&<div className="callout"><p>Saving an edit resets check states to pending. Previous research and the earlier thesis remain in review history.</p></div>}</>}
 </div><aside className="form-guide"><span className="note-icon"><Lightbulb size={20}/></span><h3>{step===0?'Clear thinking starts here.':step===1?'Make it falsifiable.':'Plan for being wrong.'}</h3><p>{step===0?'You don’t need a perfect thesis. You need an honest argument and a way to test it.':step===1?'“The yen will strengthen” is an argument. “The 2-year rate spread narrows below 200 bps” is a check.': 'A catalyst is what you’re waiting for. A risk is what could hurt. Invalidation is what would change your mind.'}</p><div className="form-guide-rule"/><small>{step===0?'All teammates share this workspace. No sign-in or personal accounts.':step===1?'For Quant and AI, use manual checks for backtest results or private experiments. Public web search cannot verify private data.':'Saving a thesis makes no API calls. Research starts only when you press Research thesis.'}</small></aside></div>{error&&<div className="form-error" role="alert"><AlertTriangle size={15}/>{error}</div>}<footer className="form-footer"><span>{step===2?`${input.groups.flatMap(g=>g.checks).filter(c=>c.label.trim()).length} checks ready to monitor`:'Your words. Testable assumptions.'}</span><div className="button-row">{step>0?<button className="button" disabled={saving} onClick={()=>{setStep(s=>s-1);setError('');}}><ArrowLeft size={14}/>Back</button>:<button className="button" onClick={onClose}>Cancel</button>}{step<2?<button className="button primary" onClick={next}>Continue<ArrowRight size={14}/></button>:<button className="button primary" disabled={saving} onClick={submit}>{saving?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>} {saving?'Saving…':existing?'Save changes':'Create thesis'}</button>}</div></footer></div></div>;
}
function Field({label,value,onChange,placeholder,textarea,required,hint,maxLength=2400}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;textarea?:boolean;required?:boolean;hint?:string;maxLength?:number}){return <label className="field"><span>{label}{required&&<b> *</b>}</span>{hint&&<small>{hint}</small>}{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={3} maxLength={maxLength}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} maxLength={maxLength}/>}</label>;}
