import type { Thesis, Group, GroupKind, Check } from './types';
function group(id:string,kind:GroupKind,claim:string,labels:string[],other:Partial<Group>={}):Group {
  return {id,kind,claim,marketView:'',variantView:'',context:'',window:'',...other,checks:labels.map((label,i):Check=>({id:`${id}-${i}`,label,type:/[><=%]|\d/.test(label)?'numeric':'qualitative',deadline:'',status:'pending',explanation:'',evidence:[]}))};
}
export const samples: Thesis[] = [
  {id:'sample-yen',version:1,title:'The case for a stronger yen',team:'SnT',desk:'FX · USDJPY',instrument:'USDJPY',direction:'Short USD / long JPY',horizon:'Next 3–6 months',summary:'A narrowing US–Japan rate differential could support the yen as Japanese policy normalises. The trade depends on a durable change in relative policy expectations, rather than a single dovish or hawkish headline.',valuation:'Relative-rate framework: look for a sustained narrowing of the 2-year yield spread. Reassess the fair-value range after each policy meeting.',tradePlan:'Express through a small short USDJPY spot position after confirmation. Define entry, stop, and target at execution; this example contains no live price targets.',groups:[
    group('yen-r1','reasoning','Policy divergence will begin to favour the yen.',['The US–Japan 2-year government bond yield spread has narrowed over the past three months.','The latest BOJ statement signals that further policy normalisation remains possible.'],{marketView:'The dollar’s yield advantage will keep the yen weak.',variantView:'The direction of the rate gap may matter more than its absolute level.'}),
    group('yen-r2','reasoning','Japanese wage growth will support persistent domestic inflation.',['The latest Japanese wage release shows positive year-on-year nominal wage growth.'],{marketView:'Domestic inflation will fade as import costs normalise.',variantView:'Wages may keep services inflation persistent.'}),
    group('yen-c1','catalyst','The next BOJ meeting provides a policy signal.',['The first BOJ policy meeting after 7 October 2026 has taken place.'],{window:'First scheduled BOJ monetary policy meeting after 7 October 2026',context:'Look for a change in the rate path and the language around wages.'}),
    group('yen-risk','risk','A renewed US inflation surprise delays easing.',['The latest US core CPI year-on-year reading is higher than the previous month.'],{context:'A widening yield advantage could support USDJPY. Size conservatively around data releases.'}),
    group('yen-invalid','invalidation','The policy-convergence argument breaks.',['The BOJ explicitly rules out further tightening over the thesis horizon.'],{context:'A confirmed reversal in policy direction would require rewriting the thesis.'}),
  ],createdAt:'2026-10-07T08:00:00Z',updatedAt:'2026-10-07T08:00:00Z',archived:false,sample:true,journal:[],reviews:[]},
  {id:'sample-ai',version:1,title:'AI infrastructure has another leg',team:'AMPB',desk:'Training · US AI',instrument:'NVDA',direction:'Long equity',horizon:'Next 2 earnings releases',summary:'Continued AI infrastructure investment could support NVIDIA’s data-centre growth. The central question is whether customer spending translates into durable revenue without eroding profitability.',valuation:'Use forward earnings and comparable companies. Test the valuation under slower growth and lower margins before deciding a target.',tradePlan:'Build a position only after checking the next earnings release. Set a price-based stop separately from the fundamental invalidation conditions.',groups:[
    group('ai-r1','reasoning','Data-centre demand remains resilient.',['NVIDIA’s latest reported data-centre revenue grew at least 40% year on year.','Management describes ongoing demand for AI infrastructure.'],{marketView:'Growth will slow sharply as customers digest capacity.',variantView:'New model training and inference demand could extend the investment cycle.'}),
    group('ai-r2','reasoning','Hyperscalers continue to invest.',['Microsoft’s latest disclosed capital expenditure is higher year on year.'],{marketView:'AI spending will soon hit a pause.',variantView:'Cloud capacity constraints may keep spending elevated.'}),
    group('ai-c1','catalyst','The next earnings release tests demand and profitability.',['NVIDIA has published its next quarterly earnings release after 7 October 2026.'],{window:'Next earnings release after thesis creation',context:'Compare both revenue growth and margins; a beat alone is insufficient.'}),
    group('ai-risk','risk','Export controls restrict the addressable market.',['A new US restriction since 7 October 2026 materially reduces NVIDIA’s permitted sales to China.']),
    group('ai-invalid','invalidation','Growth slows below the core assumption.',['NVIDIA’s latest data-centre revenue growth falls below 20% year on year.'])
  ],createdAt:'2026-10-07T07:00:00Z',updatedAt:'2026-10-07T07:00:00Z',archived:false,sample:true,journal:[],reviews:[]},
  {id:'sample-rates',version:1,title:'A softer landing for US yields',team:'SnT',desk:'Rates · US',instrument:'US 10Y',direction:'Long duration',horizon:'Next 3 months',summary:'Cooling inflation and labour demand could bring longer-dated Treasury yields lower. The thesis must account for fiscal supply and term-premium risks that can offset easier policy expectations.',valuation:'Compare the expected policy path with the Treasury curve. Treat term premium and duration risk explicitly.',tradePlan:'Consider a duration position after inflation confirmation. Define instrument, DV01, entry and stop before trading.',groups:[
    group('rates-r1','reasoning','Disinflation permits a less restrictive policy path.',['The latest US core CPI year-on-year reading is below the reading three months earlier.'],{marketView:'Inflation is too sticky for meaningful easing.',variantView:'Sequential cooling could change the policy path.'}),
    group('rates-c1','catalyst','Upcoming inflation data tests the disinflation path.',['A new CPI release after 7 October 2026 confirms a lower core year-on-year reading.'],{window:'Next monthly CPI release'}),
    group('rates-risk','risk','Fiscal supply keeps long yields elevated.',['The latest Treasury refunding announcement increases long-duration auction sizes.']),
    group('rates-invalid','invalidation','Inflation reaccelerates.',['US core CPI year-on-year has increased for three consecutive monthly releases.'])
  ],createdAt:'2026-10-07T06:00:00Z',updatedAt:'2026-10-07T06:00:00Z',archived:false,sample:true,journal:[],reviews:[]},
];
